# https://waha.devlike.pro/docs/how-to/install/
services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis_data:/data
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '10'
    env_file:
      - .env

  waha:
    restart: always
    # https://waha.devlike.pro/docs/how-to/engines/#docker-images
    # https://portal.devlike.pro/docker-image
    # image: devlikeapro/waha-plus
    # WAHA Core
    image: devlikeapro/waha:latest
    platform: linux/amd64

    # Add "dns" if you have a problem with resolving "web.whatsapp.com"
    dns:
      - 1.1.1.1
      - 8.8.8.8

    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '10'

    ports:
      - '127.0.0.1:3001:3000/tcp'

    volumes:
      # Store sessions in the .sessions folder (comment it if you're using MongoDB)
      - './sessions:/app/.sessions'

      # Save media files
      # https://waha.devlike.pro/docs/how-to/storages/#save-media-files-between-the-container-restarts
      - './media:/app/.media'

    env_file:
      - .env
    # environment:
    #   - WAHA_API_KEY=abcdefghijkltesting
    #   - WAHA_DASHBOARD_PASSWORD=abc

  http:
    build:
      context: .
      dockerfile: ./apps/http/Dockerfile
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - redis
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
    restart: always
    depends_on:
      - redis
      - waha
    # environment:
    #   - REDIS_URL=redis://redis:6379
    #   - WAHA_PUBLIC_URL=http://waha:3000
    #   - WAHA_START_SESSION=${WAHA_START_SESSION:-default}
    #   - WAHA_API_KEY=${WAHA_API_KEY}
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '10'

# NOTE: Only if you're using PostgreSQL to save sessions
# https://waha.devlike.pro/docs/how-to/storages/#media---postgresql
#  postgres:
#    image: postgres:17.6
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: postgres
#    ports:
#      - "127.0.0.1:5432:5432"
#    volumes:
#      - pg_data:/var/lib/postgresql/data
#    command:
#      - postgres
#      - "-c"
#      - "max_connections=3000"
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "100m"
#        max-file: "10"

# NOTE: Only if you're using MongoDB
# https://waha.devlike.pro/docs/how-to/storages/#sessions---mongodb
# Uncomment this block if you're using MongoDB
#  mongodb:
#    image: mongo
#    container_name: mongodb
#    ports:
#      - '127.0.0.1:27017:27017/tcp'
#    volumes:
#      - mongodb_data:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=mongouser
#      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "100m"
#        max-file: "10"

# NOTE: Only if you're using S3 to save media files
# https://waha.devlike.pro/docs/how-to/storages/#media---s3
# Uncomment this block if you're using AWS S3
#  minio:
#    image: quay.io/minio/minio
#    container_name: minio
#    restart: always
#    ports:
#      - '127.0.0.1:9000:9000'
#      - '127.0.0.1:9001:9001'
#    environment:
#      MINIO_REGION: 'eu-west-2'
#      MINIO_ROOT_USER: 'minioadmin'
#      MINIO_ROOT_PASSWORD: 'minioadmin'
#    volumes:
#      - minio_data:/data
#    command: server /data --console-address ":9001"
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "100m"
#        max-file: "10"

volumes:
  redis_data: {}
  mongodb_data: {}
  minio_data: {}
  pg_data: {}
